---
name: ci
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - lib/**
      - "*.gemspec"
      - spec/**
      - db/migrate/**
      - Rakefile
      - Gemfile
      - ".rubocop.yml"
  pull_request:
    branches:
      - master
  create:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        rails:
          - "8.1.0"
          - "8.0.0"
          - "7.2.0"
          - "7.1.0"
          - "7.0.0"
          - "6.1.0"
          - "6.0.0"
        exclude:
          - rails: "8.1.0"
            ruby: "3.1"
          - rails: "8.1.0"
            ruby: "3.0"
          - rails: "8.1.0"
            ruby: "2.7"
          - rails: "8.0.0"
            ruby: "3.1"
          - rails: "8.0.0"
            ruby: "3.0"
          - rails: "8.0.0"
            ruby: "2.7"
          - rails: "7.2.0"
            ruby: "3.0"
          - rails: "7.2.0"
            ruby: "2.7"
    env:
      APT_DEPS: libsqlite3-dev
      BUNDLE_WITHOUT: tools benchmarks docs
      RAILS_VERSION: "${{matrix.rails}}"
      RAILS_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
          bundler-cache: true
      - name: Run all tests
        run: bundle exec rake app:db:reset app:spec
